config/routes.rb
Wondercode::Application.routes.draw do

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"},
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tags do
    collection do
      post 'add'
    end
  end

  resources :repositories

  root 'tags#index'
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'dashboard', :to => 'dashboard#index'
  end

  resources :repositories do
    get ':repo' => 'repositories#show', as: 'github'
  end
  get ':user/:repo' => 'tags#show', as: 'github'

end

app/models/repository.rb
class Repository
  include Mongoid::Document

  field :name, type: String
  field :description, type: String
  field :login, type: String
  field :repo_url, type: String
  field :avatar_url, type: String
  field :languages, type: Array
  field :url, type: String
  field :type, type: Symbol

  has_and_belongs_to_many :tags

  def fullname
    "#{login}/#{name}"
  end
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :name, type: String
  
  has_and_belongs_to_many :repositories

  def to_s
    name.gsub(/::/, '/')
  end

  def user
    name.split('::').first
  end

  def repo
    name.split('::').last
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable

  field :nickname
  field :email
  field :password
  field :token
  validates_presence_of :nickname, :password

  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token.info
    if user = User.where(nickname: data["nickname"]).first
      user
    else
      user = User.create!(nickname: data["nickname"], password: Devise.friendly_token[0,20])
    end

    user.token = access_token['credentials']['token']
    user.save
    user
  end

  def octokit
    octokit = Octokit::Client.new access_token: token
  end

  def repos
    octokit.repos nickname, type: 'owner'
  end
end

app/models/vote.rb
class Vote
  include Mongoid::Document

  field :type, type: Symbol
  field :username, type: String
  field :votedate, type: DateTime

  belongs_to :user
  embedded_in :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = current_user
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /repositories
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  def show
  end

  # GET /repositories/new
  def new
    @user = current_user
    octokit = @user.octokit
    github_repo = octokit.repo owner: @user.nickname, repo: params[:repo]
    @repository = Repository.new(
      name: github_repo.name,
      repo_url: "http://github.com/#{@user.nickname}/#{github_repo.name}",
      url: github_repo.homepage,
      languages: [github_repo.language],
      description: github_repo.description
    )
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  def create
    @repository = Repository.new(repository_params.merge({
        login: current_user.nickname,
        languages: ['placeholder']
      })
    )

    if @repository.save
      redirect_to @repository, notice: 'Repository was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /repositories/1
  def update
    if @repository.update(repository_params)
      redirect_to @repository, notice: 'Repository was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /repositories/1
  def destroy
    @repository.destroy
    redirect_to repositories_url, notice: 'Repository was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      unless params[:repo].nil?
        @repository = Repository.where(login: params[:repository_id], name: params[:repo]).first
      else
        @repository = Repository.find params[:id]
      end
    end

    # Only allow a trusted parameter "white list" through.
    def repository_params
      params.require(:repository).permit(
        :name, :description, :login,
        :repo_url, :url, :type
      )
      # language is tricky
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
    @tag = Tag.where(name: "#{params[:user]}::#{params[:repo]}").first
    @repos = @tag.repositories
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render action: 'new'
    end
  end
  
  def add
    @tag = Tag.find_or_create_by(name: params[:new_tag])
    repository = Repository.find(params[:repository])
    @tag.repositories << repository
    repository.tags << @tag
    repository.save
    @tag.save
    redirect_to repositories_url
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.where(name: params[:id]).first
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    user = User.find_for_open_id(request.env["omniauth.auth"])

    if user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect user, :event => :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @repositories = Repository.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<p class="lead">Welcome <strong><%= @user.nickname %></strong>!</p>
<p class="lead">Here are your repos:</p>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Published?</th>
    </tr>
  </thead>
  <% @user.repos.each do |repo| %>
  <tr>
    <td><h4><%= repo.name %></h4></td>
    <td>
      <%= link_to "Wonderize!", new_repository_path(repo: repo.name), :class => "btn btn-primary btn-lg" %>
    </td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WonderCode</title>
  <link rel="icon" type="image/png" href="<%= image_url 'favicon.png' %>">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="container">
      <div class="row">
        <div class="span2">
          <%= link_to '/' do %>
            <%= image_tag 'logo.png' %>
          <% end %>
        </div>
        <div class="span7">
          <div id="main-text">
            <h1 class="text-center">
              "Learn by code examples"
            </h1>
          </div>
        </div>
        <div class="span3 text-right navbar-search">
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-link' %>
          <% else %>
            <%= link_to 'Login with GitHub', user_omniauth_authorize_path(:github), class: 'btn btn-link'  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container" id="main-content">
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <hr>
  <div class="container footer text-center">
    <p class="muted">WonderCoders from Wonderplex - Recife, PE | 2013</p>
  </div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44295004-1', 'wondercode.herokuapp.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :repo_url %><br>
    <%= f.url_field :repo_url %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br>
    <%= f.url_field :url %>
  </div>
  <div class="languages">
    <%= f.label :languages %><br>
    <%= f.text_area :languages %>
  </div>
  <div class="description">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.name %></td>
        <td><%= repository.repo_url %></td>
        <td><%= repository.tags.map{|t| t.name}.join","%></td>
		
        <td><%= link_to 'Show', repository %></td>
        <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
		<td><%#= link_to_function 'Tags', "$('#tags"+repository.id+"').toggle()"%></td>
		<td>
			<div id= <%#="tags#{repository.id}"%> class='hidden'/>
			    <%#= form_tag(controller: 'tags', action: 'add') do %>
			      <%#= text_field_tag :new_tag %>
				  <%#= hidden_field_tag(:repository, repository.id) %>
				  <%#= submit_tag "Add" %>
			    <%# end %>
			</div>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @repository.repo_url %>
</p>

<div id= <%="tags#{@repository.id}"%> class='hidden'/>
    <%= form_tag(controller: 'tags', action: 'add') do %>
      <%= text_field_tag :new_tag %>
    <%= hidden_field_tag(:repository, @repository.id) %>
    <%= submit_tag "Add" %>
    <% end %>
</div>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class="centered-content text-center">
  <h1 class="text-center">Find me projects using:</h1>
  <hr>

  <% @tags.each do |tag| %>
    <%= link_to tag, github_path(user: tag.user, repo: tag.repo), class: 'thumbnail tag' %>
  <% end %>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<div class="margin">
  <h3 class="muted">Code examples for <strong><%= @tag %></strong></h3>
</div>

<% @repos.each do |repo| %>
  <div class="repo-wrapper thumbnail">
    <div class="content">

      <div class="details pull-left">
        <img src="<%= repo.avatar_url %>" class="img-rounded pull-left">
        <div class="text">
          <h4>
            <%= link_to repo.fullname, repo.repo_url, target: repo.fullname %>
          </h4>
          <p><%= repo.description %></p>
        </div>
      </div>

      <div class="tags pull-right">
        <p class="muted">This project uses:</p>
        <% repo.tags.each do |t| %>
          <%= link_to t, github_path(user: t.user, repo: t.repo), class: 'thumbnail tag' %>
        <% end %>
      </div>

      <div class="clearfix"></div>
    </div>
    <div class="languages">
      <% unless repo.tags.empty? %>
        <%= repo.languages.join ', ' %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/welcome/index.html.erb
<% @repositories.each do |repo| %>
  <div class="repo-wrapper thumbnail">
    <div class="content">

      <div class="details pull-left">
        <img src="<%= repo.avatar_url %>" class="img-rounded pull-left">
        <div class="text">
          <h4>
            <%= link_to repo.fullname, repo.repo_url, target: repo.fullname %>
          </h4>
          <p><%= repo.description %></p>
        </div>
      </div>

      <div class="tags pull-right">
        <% 4.times do |i| %>
          <div class="tag">
            <a href="#" class="rate btn btn-mini up"><%= image_tag 'up.png', width: 14 %></a>
            <a href="#" class="rate btn btn-mini down"><%= image_tag 'down.png', width: 14 %></a>
            <div class="count">
              +<%= i*4 %>
            </div>
            <div class="name">
              Tests with capybara <%= i*4 %>
            </div>
          </div>
        <% end %>

        <% unless repo.tags.empty? %>
          <%= repo.tags.map{|t| t.name}.join","%>
        <% end %>
        <!-- <a href="#" class="btn btn-success">Make Review</a> -->
      </div>

      <div class="clearfix"></div>
    </div>
    <div class="languages">
      <% unless repo.tags.empty? %>
        <%= repo.languages.join ', ' %>
      <% end %>
    </div>

  </div>
<% end %>